sudo: required
language: node_js
notifications:
  slack:
    secure: iaTWG9GXJ83P+KLUmoUGwxQPzNeZqhPnc1qybi7tFj70WJPQrhymYTS03CoVPVq6K67P68p5vyxQ/IMCLDF6DlK/7EuSm/9H0TexEw1CzLt5UPqPycBCxxU5A0Y4tUndr6Wb7/BMxbqMSc2t5UfBzc60S4XA5gpSvhUNXGQV8u0fatr/Pj0O0Ks6885mIJKXTx4eW9aLAPzFod7u0guR64iSvvHyglL+UhodsrWbkTo114HiCur0s/fLM+WGciyGZlFtUXUKYVDQLPKxYelBb0Xv/TdvOxLAIATVAz2UmJ1LTHwlpYMKYcD1fHWtGFWTIOrqfBK9OpNoO/T2YDVil+y1qas18gGOig2ov7JmcEjyjmx0hH3Xs/7twXxkyBz4UZP7uqXzhWxuSFDh8TXjUDT2nTh5Z7/l5fz9CmNxGq8itCKzMPdAuf5uPKheAy9UHVFr92TggncFBYsFEwuMvI6ydo3b2D4hWKH/5550NF8HDJD05H0hbx1ByYqUibzqTMpqtYoSLkVCdMJp6YlOwfPwxsXRx+fM9W9pjEjys4Kyrf3jCguksHLvl/pCj8l3ogpyZWo5VVON733doM4zb3RMIdlTR3B5YNeOo7sFgWfS6ib2g6wKWEZsft5akySE35vDdyP2S+GrUNh2na0xQmVQdP3tEAC9v492E7Kt9vY=
  email:
  - kelvinomereshone@gmail.com
